name: determine-java-server-version
run-name: grabbing latest java server version
on:
 schedule:
  - cron: 20 4 * * *
jobs:
 run-minecraft-launcher:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout 
     uses: actions/checkout@v4
   - name: Setting permissions to execute script
     run: chmod u+x start-mc-launcher.sh
   - name: Start minecraft launcher and write new version file
     run: ./start-mc-launcher.sh
   - name: Commit and push new version
     run: |
      git config --global user.name '${{ github.actor }}'
      git config --global user.email '${{ github.actor }}@users.noreply.github.com'
      git commit -am "[automated] update java server version"
      git push