name: determine-java-server-version
run-name: grabbing latest java server version
on:
 schedule:
  - cron: 20 4 * * *
jobs:
 run-minecraft-launcher:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout 
     uses: actions/checkout@v4
     with:
      fetch-depth: 2
   - name: Setting permissions to execute script
     run: chmod u+x start-mc-launcher.sh
   - name: Start minecraft launcher and write new version file
     run: ./start-mc-launcher.sh
   - name: Check upon diff
     id: check-diff
     run: |
      newVersionAvailable=$(git diff java_version_latest.json)
      echo "DIFF_OUTPUT=${newVersionAvailable}" >> "$GITHUB_OUTPUT"
      echo "Length of diff: ${#newVersionAvailable}"
   - name: Commit and push new version when changed
     env:
      DIFF_OUTPUT: ${{ steps.check-diff.outputs.DIFF_OUTPUT }}
     run: |
      if [ ${#DIFF_OUTPUT} -gt 0 ]
      then
       git config --global user.name '${{ github.actor }}'
       git config --global user.email '${{ github.actor }}@users.noreply.github.com'
       git commit -am "[automated] update java server version"
       git push
      else
       echo "No new Minecraft Java Edition available."
      fi